//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyCsharpProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BabyCsharpProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace LearningSpace
        ///{
        ///	static class Program
        ///	{
        ///		static void Main(string[] args)
        ///		{
        ///			Console.WriteLine(&quot;Give me an integer&quot;);
        ///			int a = Convert.ToInt32(Console.ReadLine());
        ///			Console.WriteLine(&quot;Give me another integer&quot;);
        ///			int b = Convert.ToInt32(Console.ReadLine());
        ///			int c = a+b;
        ///			Console.WriteLine(&quot;The sum of those integers is:&quot;+c);
        ///			Console.ReadLine();
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string a_b_Text {
            get {
                return ResourceManager.GetString("a+b.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace LearningSpace
        ///{
        ///	static class Program
        ///	{
        ///		static void Main(string[] args)
        ///		{
        ///			//Your code goes here!
        ///			bool correct = false;
        ///           			int guess = 69;
        ///           			Console.WriteLine(&quot;Can you guess what integer Im thinking of?&quot;);
        ///            			while (correct == false)
        ///            			{
        ///               				int userGuess = Convert.ToInt32(Console.ReadLine());
        ///                			if(userGuess == guess)
        ///                			{
        ///                    				Console.WriteLi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Guessing {
            get {
                return ResourceManager.GetString("Guessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace LearningSpace
        ///{
        ///	static class Program
        ///	{
        ///		static void Main(string[] args)
        ///		{
        ///			Console.WriteLine(&quot;Hello World&quot;);
        ///			Console.ReadLine();
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string HelloWorld_Text {
            get {
                return ResourceManager.GetString("HelloWorld.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace LearningSpace
        ///{
        ///	static class Program
        ///	{
        ///		static void Main(string[] args)
        ///		{
        ///            			Console.WriteLine(&quot;Enter option desired: \n\t0\n\t1\n\t2\n&quot;);
        ///          		 	int number = Convert.ToInt32(Console.ReadLine());
        ///
        ///            			switch (number)
        ///            			{
        ///               	 			case 0:
        ///               				     Console.WriteLine(&quot;General Kenobi...&quot;);
        ///				     Console.ReadLine();
        ///               				     break;
        ///
        ///                			case 1:
        ///                			 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Kenobi {
            get {
                return ResourceManager.GetString("Kenobi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace LearningSpace
        ///{
        ///	static class Program
        ///	{
        ///		static void Main(string[] args)
        ///		{
        ///			//Your code goes here!
        ///			int a = 4;
        ///			int b = 3;
        ///			int c = a/b;
        ///			int d = a%b;
        ///			int e = (a+b*2)/(a-b);
        ///			double z = 124.6423;
        ///			double y = 3057.023751;
        ///			double x = b/a;
        ///			Console.Write(&quot;a = &quot;+a+&quot;\nb= &quot;+b+&quot;\nc= &quot;+c+&quot;\nd= &quot;+d+&quot;\ne= &quot;+e+&quot;\nz= &quot;+z+&quot;\ny= &quot;+y+&quot;\nz= &quot;+z);
        ///			Console.ReadLine();//This will output any Console.WriteLine commands in the code
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string MathExample {
            get {
                return ResourceManager.GetString("MathExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace LearningSpace
        ///{
        ///	static class Program
        ///	{
        ///		static void Main(string[] args)
        ///		{
        ///			//Your code goes here!
        ///			
        ///			Console.Write(&quot;Give me your name:&quot;);
        ///			string name = Console.ReadLine();
        ///			Console.Write(&quot;Hello &quot; + name);
        ///			Console.ReadLine();
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace LearningSpace
        ///{
        ///	static class Program
        ///	{
        ///		static void Main(string[] args)
        ///		{
        ///			//Your code goes here!
        ///           			 Console.WriteLine(&quot;Enter an integer : &quot;);
        ///           			 int n = Convert.ToInt32(Console.ReadLine());
        ///           			 if(n%2==0)
        ///            			{
        ///               				 Console.WriteLine(n+&quot; is even&quot;);
        ///            			}
        ///            			else
        ///            			{
        ///                			Console.WriteLine(n+&quot; is odd&quot;);
        ///            			}
        ///			Console.ReadLine();//This [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OddEven {
            get {
                return ResourceManager.GetString("OddEven", resourceCulture);
            }
        }
    }
}
